### ISSUE TITLE
UnboundLocalError: local variable 'total_loss' referenced before assignment

### ISSUE THREAD

**Issue by SeekPoint** [JayYip/cws-tensorflow#1]
(venv) mldl@mldlUB1604:~/ub16_prj/cws-tensorflow$ 
(venv) mldl@mldlUB1604:~/ub16_prj/cws-tensorflow$ python3 train.py --input_file_dir="data\output_dir" --train_dir="save_model" --log_every_n_steps=10
/home/mldl/ub16_prj/VENV_host/py3tf1.4/venv/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Building model...
CRITICAL:tensorflow:Found no input files matching data\output_dir/*.TFRecord
Setting up training ops...
/home/mldl/ub16_prj/VENV_host/py3tf1.4/venv/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Start Training...
2018-06-30 01:43:28.345409: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-06-30 01:43:28.418344: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-30 01:43:28.418650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.24GiB
2018-06-30 01:43:28.418668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
INFO:tensorflow:Restoring parameters from save_model/model.ckpt-0
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path save_model/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Caught OutOfRangeError. Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    tf.app.run()
  File "/home/mldl/ub16_prj/VENV_host/py3tf1.4/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 133, in main
    session_config=sess_config)
  File "/home/mldl/ub16_prj/VENV_host/py3tf1.4/venv/lib/python3.5/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 783, in train
    return total_loss
UnboundLocalError: local variable 'total_loss' referenced before assignment
(venv) mldl@mldlUB1604:~/ub16_prj/cws-tensorflow$

**Comment by JayYip** [comment]
You may want to check whether your data is damaged.

**Comment by SeekPoint** [comment]
can you list the directory with 'tree' command

**Comment by Cuzzie** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.Stephen1993, @nguyenduchuyz190, @haven-jeon, @sevmeowple, @sergedeh, @FateDawnLeon, @shunmaruko, @shuyingsunshine2023, @imrohankataria, @keitap, @WinstonFassett, @d0gz, @Hailie17, @puzzithinker, @t-alfers, @cin-hubert, @hj3938, @lkyhfx, @WalkJim197, @Geekstark
